### ISSUE TITLE
Caching onto queries to speed up the process

### ISSUE THREAD

**Issue by Bjwebb** [NRGI/resource-projects-etl#17]
In this commit - https://github.com/NRGI/resource-projects-etl/commit/6473673d5a4735b1b986bebb576c2f680ef5fb4c - I do some more caching that speeds up script runs considerably.

@timgdavies Does this look safe to be running? I'm assuming that the ontology is essentially immutable after it's been loaded, and a query with the same sparql text should always return the same result, is that correct?

**Comment by timgdavies** [comment]
Ah-ha. Yes - that looks good - and correct that the ontology is immutable. 

Thanks!
