### ISSUE TITLE
Dataset: Kosmos Energy

### ISSUE THREAD

**Issue by timgdavies** [NRGI/resource-projects-etl#18]
Kosmos provide an image with a table of project level payments at http://www.kosmosenergy.com/responsibility/transparency.php

This needs to be transcribed, and can then be set-up for loading onto the platform.

**Comment by davidmihalyi** [comment]
Done the manual input into spreadsheet:
https://docs.google.com/spreadsheets/d/1sPZm9-0SkDaK9g-RALtY58uEdvuFGOnZLu7qJAhzNqg/edit#gid=0

Now loading it into template provided.

**Comment by timgdavies** [comment]
Thanks @davidmihalyi  - Let me know when all mapped into the template and do log any issues you hit during the process.

**Comment by davidmihalyi** [comment]
done!
https://docs.google.com/spreadsheets/d/18nucm2qWFjrRilpnaKFC0A8U-myZxdJN8dSYU2r_ZzY/edit#gid=1333644202

**Comment by timgdavies** [comment]
Tracking of datasets now handled here: https://docs.google.com/spreadsheets/d/1_p_Ku927TDlBKdkwpbxU3uSOeSdubZIyb7d1KONelPA/edit#gid=0
