### ISSUE TITLE
What encoding is eiti-project-level.csv ?

### ISSUE THREAD

**Issue by Bjwebb** [NRGI/resource-projects-etl#20]
(https://github.com/NRGI/resource-projects-etl/blob/taglifter/process/eiti-projects/sources/eiti-project-level.csv)

`file` says

```
sources/eiti-project-level.csv: Non-ISO extended-ASCII text, with very long lines
```

This is also causing errors with the import script for me. Would be better to use utf-8 (which Python 3 supports for CSVs out of the box).

@timgdavies Have you got some other copy of this spreadsheet that you might be able to re-save as a utf-8 csv?

**Comment by timgdavies** [comment]
It was saved from Excel on Mac - which does not seem to offer me any good encoding options when saving.

However, running it through `iconv` (building on [Paul's assumptions here](http://blog.whatfettle.com/2014/10/13/one-csv-thirty-stories-bootstrapping/)) seems to generate a UTF-8 file

`cat sources/eiti-project-level.csv | iconv -f ISO-8859-1 -t UTF-8 > sources/eiti-project-level-utf8.csv`

which could be used. We might want to think about how we add some tolerance for file encoding variations to our standard transform process - as I suspect this will be a common problem with incoming data.

**Comment by Bjwebb** [comment]
That leads to output like ![image](https://cloud.githubusercontent.com/assets/634/8452542/aad0b986-1fe3-11e5-92bf-83ed35542491.png).

I think the problem is that you've imported google's spreadsheet (which is utf-8) into excel as if it were ISO-8859-1/Windows code page.

**Comment by timgdavies** [comment]
OK. Will look at re-running the markup of this EITI data in future through Refine - rather than Excel - but will need to leave that to a future point.

**Comment by timgdavies** [comment]
We're now reading via Google Spreadsheets in most cases, which seems to deal with encoding issues.
