### ISSUE TITLE
Add resource-projects-ontology.rdf to default load process

### ISSUE THREAD

**Issue by timgdavies** [NRGI/resource-projects-etl#21]
Having the ontology within our triple store will support easier querying over data.

**Comment by Bjwebb** [comment]
Actually, not sure whether this is working, can't actually see any triples I'd associate with the ontology in virtuoso.

Should there need to be any sort of special procedure for this (beyond just loading it with the other files)?

**Comment by timgdavies** [comment]
It looks like it is working to me...

The query below returns triples that could only be coming from the ontology:

``` sparql

select distinct * where { <http://resourceprojects.org/def/Company> ?p ?o} LIMIT 100

```

**Comment by Bjwebb** [comment]
Thanks, that does look like it worked. I think the problem might have been that I was reading the RDF triples backwards.
