### ISSUE TITLE
UUID generation

### ISSUE THREAD

**Issue by Bjwebb** [NRGI/resource-projects-etl#22]
In the process of converting to Python 3, I switched from time based to random 64 bit UUIDs - https://github.com/NRGI/resource-projects-etl/commit/7ef59b7084b49ef297d88f4d0e0ed21ccc48390b

Might be worth thinking about whether this does make sense or not. I don't think 64bit UUIDs are actually much of a thing outside the one library you were using, so it might be worth looking at something that gives us greater information density (so that the IDs can be more unique or shorter), e.g. a longer version of the random alphanumeric string used in project ids.

**Comment by timgdavies** [comment]
Very happy to explored an alternative approach to UUIDs from the current one - particularly if we can get to shorter UUIDs. 

I've not done the maths on how many bits we need to be confident of avoiding collisions given the scale of data we are dealing with - but perhaps that is worth doing?

**Comment by timgdavies** [comment]
The taglifter library now has it's own random function, which doesn't worry about 64 Bit UUIDs.

It also includes a syntax for each class in the ontology to specific an identifier pattern that should be used when constructing identifiers.
