### ISSUE TITLE
Country Codes

### ISSUE THREAD

**Issue by caprenter** [NRGI/resource-projects-etl#30]
Some country codes are coming in as e.g. UK, Uk and so on. Are we testing against a code list on import.
Is that a good way to deal with the issue below?

![image](https://cloud.githubusercontent.com/assets/185467/8589618/23d22ffe-2610-11e5-98d3-dd6ff5475ebd.png)

**Comment by timgdavies** [comment]
Two options here:

(1) Tighten up the import scripts (requires more custom handling in the tag-lifter script... so I'm cautious about that);

(2) Have a process to drop all country names, and re-import against ISO code from an authoritative list;

I suspect (2) might be the better option for the moment - but will review...

**Comment by timgdavies** [comment]
I've updated the way country codes are generated in TagLifter which should address the ID side of this, we might still need to look at queries and part of (2) to avoid the multiple labels problem.
