### ISSUE TITLE
Considering provenance vs. auditing trail

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resource-projects-etl#4]
Provenance can be documented by sources from across time. 

The auditing trail should include: 
- was information provided by machine
- who authorised it

**Comment by timgdavies** [comment]
We should soon have provenance on a number of levels:

(1) In the input templates, most rows ask for the Source to be given, linking to the class to a given source;

(2) The conversion process logs which sheet and row data came from;

(3) Each imported file is loaded into it's own named graph, which allows us to identify where each item of data originated;

**Comment by timgdavies** [comment]
Pages all have a Source which gives provenance to the graph, source and file number.
