### ISSUE TITLE
Draft alpha load template

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resource-projects-etl#6]
Prepare load template - as first pass - for May 27th workshop, in GoogleDoc.

**Comment by timgdavies** [comment]
We didn't get chance to work on this ahead of the workshop. Were there discussions in the May 27th session which should inform the next stage of work on this.

We have been looking at HXL, and some existing templates to inform this work in the coming week.

**Comment by timgdavies** [comment]
The template is being kept up to date here: https://drive.google.com/open?id=19pLirq9l-4W0DudIxb_P5KEMx6HP2smxDksUBVoyQ3I
