### ISSUE TITLE
View on staging/live links do not do anything

### ISSUE THREAD

**Issue by Bjwebb** [NRGI/resource-projects-etl#63]
Not entirely sure what these should link to atm. Should we just drop the links?

**Comment by timgdavies** [comment]
Can you grey them out for now. I think in future we might want them in future - pointing to a service which summarises the data in each graph - but that will have to wait for now.

**Comment by Bjwebb** [comment]
Okay, will do.

**Comment by Bjwebb** [comment]
Actually, which is more useful in the short term, greyed out, or a link to the index page of staging/live (I'm thinking since, in the short term, the staging site won't have a short URL this might be quite useful).

**Comment by timgdavies** [comment]
A link to the index page sounds good :)

**Comment by Bjwebb** [comment]
These now link to the index pages.
