### ISSUE TITLE
Tried to load Ghana data but crashed

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/resource-projects-etl#67]
Here is google doc:
https://docs.google.com/spreadsheets/d/1SM6TEDpVIAMOSN_b2zF8LnoPezOveihOM3zqC9FLZNU/edit#gid=2062331779

Here is bug descript:
ValueError at /
Expecting value: line 2 column 1 (char 1)

**Comment by timgdavies** [comment]
Try now.

Documents need to be published to the web, as well as shared with view access.

To publish to the web, use the 'File > Publish to the Web' menu option.

I've done that for this document.

**Comment by davidmihalyi** [comment]
thanks, and indeed, this is something you told me, but forgot. 

i tried again, but crashed while converting. Seems like an erroneous entry but not sure how I can locate it. 

ValueError at /dataload/16/convert
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Request Method: POST
Request URL:    http://etl.nrgi-dev.default.opendataservices.uk0.bigv.io/dataload/16/convert
Django Version: 1.8.5
Exception Type: ValueError
Exception Value:  
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Exception Location: /usr/local/lib/python3.4/dist-packages/pandas/core/generic.py in **nonzero**, line 730
Python Executable:  /usr/bin/python3
Python Version: 3.4.0
Python Path:  
['/usr/src/resource-projects-etl',
 '/usr/local/bin',
 '/usr/src/resource-projects-etl/src/cove',
 '/usr/src/resource-projects-etl/src/flattentool',
 '/usr/local/lib/python3.4/dist-packages/resource_projects_etl-0.0.0-py3.4.egg',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/usr/lib/python3.4/lib-dynload',
 '/usr/local/lib/python3.4/dist-packages',
 '/usr/lib/python3/dist-packages']
Server time:    Mon, 16 Nov 2015 11:42:22 +0000

**Comment by timgdavies** [comment]
This was down to an issue on the alias page that is fixed in updated templates. Any new files should not have this problem.
