### ISSUE TITLE
Flagging duplicates on staging server

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/resource-projects-etl#72]
Pushed updated Phillippines data to staging server, but produces multiple company duplicates:
http://resourceprojects-staging.nrgi-dev.default.opendataservices.uk0.bigv.io/country/PH.html

just flagging

**Comment by timgdavies** [comment]
Please hold off on any changes to staging or live servers right now. We're working on development branch - and will let you know when deployed and ready for testing

**Comment by davidmihalyi** [comment]
Sure, will hold off!

David Mihalyi | Economic Analyst
Natural Resource Governance Institute
(formerly the Revenue Watch Institute – Natural Resource Charter)
1 Knightrider Court, London EC4V 5BJ, UK  |
Office: +44 20 7332 6118 | Mob: +44 (0) 77 9858 6290
dmihalyi@resourcegovernance.orgmailto:dmihalyi@resourcegovernance.org | www.resourcegovernance.org | Skype: davidmihalyi
